apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-persist-volume-claim
      containers:
        - name: redis-deployment
          image: docker.io/library/redis:5.0-alpine3.15
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-volume
              mountPath: /data
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-configmap
                  key: redis.port
