apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-persist-volume
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
  storageClassName: shared
