apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persist-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared
  resources:
    requests:
      storage: 256Mi
