# Generated by Django 4.1.7 on 2023-03-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=10000)),
                ('status', models.CharField(choices=[('none', 'in_progress'), ('in_progress', 'in_progress')], max_length=10000)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juera_app.upload')),
            ],
        ),
    ]
