# Generated by Django 4.1.7 on 2023-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juera_app', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('executed', 'executed')], max_length=10000),
        ),
    ]
