# Generated by Django 4.1.7 on 2023-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juera_app', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('executed', 'executed')], default='none', max_length=10000),
        ),
    ]
