apiVersion: v1
kind: ConfigMap
metadata:
  name: link-shortener-configmap
data:
  app.ip: "0.0.0.0"
  app.port: "8000"
  redis.serviceName: "redis-service"
  redis.port: "6379"
  cache.timeOut: "5"

---

apiVersion: v1
kind: Secret
metadata:
  name: link-shortener-secret
type: Opaque
stringData:
  rebrandly.key: YTVhZmM0OTliZTE1NDcxOGFjYzRiNjEwNWI4ZDM1MDY=
  rebrandly.api: aHR0cHM6Ly9hcGkucmVicmFuZGx5LmNvbS92MS9saW5rcw==
