apiVersion: v1
kind: Service
metadata:
  name: link-shortener-service
spec:
  selector:
    app: link-shortener-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
    